# version: '2.3'

services:
  init:
    container_name: init
    image: python:3.10-slim
    command: ["sh", "-c", "echo 'Starting services'; sleep 30; echo 'initialization is completed'"]
    restart: "no"
    networks:
      - my_network

  rag_engine:
    restart: always
    container_name: rag_engine
    mem_limit: 2600m
    build:
      context: ./rag_engine
      dockerfile: Dockerfile
    image: rag_engine:latest
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMBEDDER_URL=${EMBEDDER_URL}
    volumes:
      - ./rag_engine:/rag_engine
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port ${RAG_ENGINE_PORT}"
    ports:
      - ${RAG_ENGINE_PORT}:${RAG_ENGINE_PORT}
    depends_on:
      - mysql
      - embedder
      - neural_worker
    networks:
      - my_network

  neural_worker:
    restart: always
    container_name: neural_worker
    mem_limit: 4G
    build:
      context: ./neural_worker
      dockerfile: Dockerfile
    image: neural_worker:latest
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port ${WORKER_PORT}"
    environment:
      - BASE_GPT_URL=${BASE_GPT_URL}
      - GPT_TOKEN=${GPT_TOKEN}
    volumes:
      - ./neural_worker:/neural_worker
    ports:
      - ${WORKER_PORT}:${WORKER_PORT}
    networks:
      - my_network

  embedder:
    restart: always
    container_name: embedder
    mem_limit: 4G
    build:
      context: ./embedder
      dockerfile: Dockerfile
    image: embedder:latest
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port ${EMBEDDER_PORT}"
    environment:
      - CUDA_VISIBLE_DEVICES_EMB=${CUDA_VISIBLE_DEVICES_EMB}
      - SPECIFIC_MODEL=${SPECIFIC_MODEL}
      - TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE}
    volumes:
      - ./embedder:/embedder
      - /home/orange_lime/.cache/huggingface/hub:/cache/
    ports:
      - ${EMBEDDER_PORT}:${EMBEDDER_PORT}
    networks:
      - my_network
 
  mysql:
    restart: always
    container_name: mysql
    mem_limit: 500m
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "my_network"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  my_network:
    driver: bridge
# version: '2.3'

# services:
#   init:
#     container_name: init
#     image: python:3.10-slim
#     command: ["sh", "-c", "echo 'Starting services'; sleep 30; echo 'initialization is completed'"]
#     restart: "no"
#     networks:
#       - my_network

#   rag_engine:
#     restart: always
#     container_name: rag_engine
#     mem_limit: 2600m
#     build:
#       context: ./rag_engine
#       dockerfile: Dockerfile
#     image: rag_engine:latest
#     environment:
#       - DB_NAME=${DB_NAME}
#       - DB_USER=${DB_USER}
#       - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT}
#       - EMBEDDER_URL=${EMBEDDER_URL}
#     volumes:
#       - ./rag_engine:/rag_engine
#     command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port ${RAG_ENGINE_PORT}"
#     ports:
#       - ${RAG_ENGINE_PORT}:${RAG_ENGINE_PORT}
#     depends_on:
#       - mysql
#       - embedder
#       - neural_worker
#     networks:
#       - my_network

#   neural_worker:
#     restart: always
#     container_name: neural_worker
#     mem_limit: 4G
#     build:
#       context: ./neural_worker
#       dockerfile: Dockerfile
#     image: neural_worker:latest
#     command: bash -c "uvicorn main:app --host 0.0.0.0 --port ${WORKER_PORT}"
#     environment:
#       - BASE_GPT_URL=${BASE_GPT_URL}
#       - GPT_TOKEN=${GPT_TOKEN}
#     volumes:
#       - ./neural_worker:/neural_worker
#     ports:
#       - ${WORKER_PORT}:${WORKER_PORT}
#     networks:
#       - my_network

#   embedder:
#     restart: always
#     container_name: embedder
#     mem_limit: 4G
#     build:
#       context: ./embedder
#       dockerfile: Dockerfile
#     image: embedder:latest
#     command: bash -c "uvicorn main:app --host 0.0.0.0 --port ${EMBEDDER_PORT}"
#     environment:
#       - CUDA_VISIBLE_DEVICES_EMB=${CUDA_VISIBLE_DEVICES_EMB}
#       - SPECIFIC_MODEL=${SPECIFIC_MODEL}
#       - TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE}
#     volumes:
#       - ./embedder:/embedder
#       - /home/orange_lime/.cache/huggingface/hub:/cache/
#     ports:
#       - ${EMBEDDER_PORT}:${EMBEDDER_PORT}
#     networks:
#       - my_network
 
#   mysql:
#     restart: always
#     container_name: mysql
#     mem_limit: 500m
#     image: mysql:5.6
#     environment:
#       - MYSQL_DATABASE=${DB_NAME}
#       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
#     volumes:
#       - ./mysqldata:/var/lib/mysql
#       - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
#     ports:
#       - ${DB_PORT}:${DB_PORT}
#     networks:
#       - my_network
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "my_network"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 30s

# networks:
#   my_network:
#     driver: bridge
