# apiVersion: v1
# kind: Secret
# metadata:
#   name: nextcloud-secret
#   labels:
#     app: nextcloud
# type: Opaque
# stringData:
#   NEXTCLOUD_ADMIN_PASSWORD: "very_bad_password"
# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: nextcloud
#   labels:
#     app: nextcloud
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nextcloud
#   template:
#     metadata:
#       labels:
#         app: nextcloud
#     spec:
#       containers:
#       - name: nextcloud
#         image: docker.io/nextcloud:stable-apache
#         resources:
#           limits:
#             cpu: 500m
#             memory: 256Mi
#           requests:
#             cpu: 250m
#             memory: 128Mi
#         ports:
#         - name: http
#           containerPort: 80
#           protocol: TCP
#         env:
#         - name: NEXTCLOUD_UPDATE
#           value: '1'
#         - name: ALLOW_EMPTY_PASSWORD
#           value: 'yes'
#         - name: POSTGRES_HOST
#           value: postgres-service
#         - name: POSTGRES_DB
#           valueFrom:
#             configMapKeyRef:
#               name: postgres-configmap
#               key: POSTGRES_DB
#         - name: NEXTCLOUD_TRUSTED_DOMAINS
#           value: "127.0.0.1"
#         - name: POSTGRES_USER
#           valueFrom:
#             configMapKeyRef:
#               name: postgres-configmap
#               key: POSTGRES_USER
#         - name: POSTGRES_PASSWORD
#           valueFrom:
#             configMapKeyRef:
#               name: postgres-configmap
#               key: POSTGRES_PASSWORD
#         - name: NEXTCLOUD_ADMIN_USER
#           value: any_name_you_want
#         - name: NEXTCLOUD_ADMIN_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: nextcloud-secret
#               key: NEXTCLOUD_ADMIN_PASSWORD
#         imagePullPolicy: IfNotPresent
#       restartPolicy: Always
#       dnsPolicy: ClusterFirst

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: docker.io/nextcloud:stable-apache
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: postgres-configmap
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: nextcloud-configmap
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 7
          periodSeconds: 8
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 7
          periodSeconds: 8
      restartPolicy: Always
      dnsPolicy: ClusterFirst